<?php

declare(strict_types=1);

namespace Sigilbase\Verifier\Tests;

use RuntimeException;
use ZipArchive;

/**
 * Generates evidence bundles from scratch — its own Ed25519 keypair, its
 * own hash chain, its own Merkle trees — using the verifier's canonical
 * JSON and Merkle functions (verify.php is require()d as a library; its
 * CLI does not run when required). The bundles are structurally identical
 * to real Sigilbase exports at format 1.1 minus the optional anchor and
 * consistency files, which the format marks optional.
 *
 * Payloads deliberately include non-ASCII keys and astral-plane characters
 * so canonical key ordering (UTF-16 code units, no mbstring) is exercised
 * end to end.
 */
final class FixtureGenerator
{
    // No type on the constant: typed class constants are PHP 8.3+ and this
    // repository supports 8.2.
    private const ZERO_HASH = '0000000000000000000000000000000000000000000000000000000000000000';

    public readonly string $streamId;

    public readonly string $publicKeyHex;

    private readonly string $secretKey;

    /**
     * A fresh random key and stream by default. A seed (32 bytes, hex) and a
     * stream id make the output deterministic, which is what the committed
     * consistency fixtures in corpus/ need: they are generated by
     * tools/build-corpus-consistency.php under the published corpus test key
     * and must come out byte for byte the same on every machine.
     */
    public function __construct(?string $seedHex = null, ?string $streamId = null)
    {
        require_once __DIR__.'/../verify.php';

        $keypair = $seedHex === null
            ? sodium_crypto_sign_keypair()
            : sodium_crypto_sign_seed_keypair((string) hex2bin($seedHex));

        $this->secretKey = sodium_crypto_sign_secretkey($keypair);
        $this->publicKeyHex = bin2hex(sodium_crypto_sign_publickey($keypair));

        if ($streamId !== null) {
            $this->streamId = $streamId;

            return;
        }

        // Random per instance: two generators are two different streams,
        // exactly like two different Sigilbase customers.
        $hex = bin2hex(random_bytes(16));
        $this->streamId = sprintf(
            '%s-%s-%s-%s-%s',
            substr($hex, 0, 8),
            substr($hex, 8, 4),
            substr($hex, 12, 4),
            substr($hex, 16, 4),
            substr($hex, 20, 12),
        );
    }

    /**
     * Write a valid bundle of $eventCount events sealed into checkpoints of
     * $perCheckpoint into $dir. $payloadSalt varies the event CONTENT while
     * keeping the stream identity: two bundles from the same generator with
     * different salts are the same stream telling two different histories —
     * the thing consistency proofs exist to catch.
     */
    public function writeBundle(string $dir, int $eventCount = 4, int $perCheckpoint = 2, string $payloadSalt = ''): string
    {
        if (! is_dir($dir) && ! mkdir($dir, 0755, true)) {
            throw new RuntimeException("could not create [{$dir}]");
        }

        $events = [];
        $prevHash = self::ZERO_HASH;

        foreach (range(1, $eventCount) as $sequence) {
            $payload = (object) [
                'n' => $sequence,
                'rôle' => 'admin'.$payloadSalt,
                'note' => "käse 𝄞 clef #{$sequence}",
            ];

            $payloadHash = hash('sha256', canonical_encode($payload));

            $occurredAt = sprintf('2026-07-01T09:%02d:00.000000Z', $sequence);
            $receivedAt = sprintf('2026-07-01T09:%02d:01.500000Z', $sequence);

            $entryHash = hash('sha256', canonical_encode((object) [
                'v' => 1,
                'stream' => $this->streamId,
                'seq' => $sequence,
                'occurred_at' => $occurredAt,
                'received_at' => $receivedAt,
                'actor' => "user:{$sequence}",
                'action' => 'role.granted',
                'resource' => "user:9f{$sequence}",
                'payload_hash' => $payloadHash,
                'prev' => $prevHash,
            ]));

            $events[] = (object) [
                'v' => 1,
                'seq' => $sequence,
                'occurred_at' => $occurredAt,
                'received_at' => $receivedAt,
                'actor' => "user:{$sequence}",
                'action' => 'role.granted',
                'resource' => "user:9f{$sequence}",
                'payload' => $payload,
                'payload_hash' => $payloadHash,
                'prev_hash' => $prevHash,
                'entry_hash' => $entryHash,
            ];

            $prevHash = $entryHash;
        }

        $checkpoints = [];
        $prevCheckpointHash = self::ZERO_HASH;

        foreach (array_chunk($events, $perCheckpoint) as $chunk) {
            $from = $chunk[0]->seq;
            $to = $chunk[count($chunk) - 1]->seq;

            $root = bin2hex(merkle_root(array_map(
                static fn (object $event): string => (string) hex2bin($event->entry_hash),
                $chunk,
            )));

            $createdAt = sprintf('2026-07-01T09:%02d:30.000000Z', $to);

            $checkpointHash = hash('sha256', canonical_encode((object) [
                'v' => 1,
                'stream' => $this->streamId,
                'from' => $from,
                'to' => $to,
                'root' => $root,
                'prev_checkpoint' => $prevCheckpointHash,
                'created_at' => $createdAt,
            ]));

            $checkpoints[] = (object) [
                'v' => 1,
                'stream' => $this->streamId,
                'from' => $from,
                'to' => $to,
                'root' => $root,
                'prev_checkpoint' => $prevCheckpointHash,
                'created_at' => $createdAt,
                'checkpoint_hash' => $checkpointHash,
                'signature' => bin2hex(sodium_crypto_sign_detached((string) hex2bin($checkpointHash), $this->secretKey)),
                'public_key' => $this->publicKeyHex,
            ];

            $prevCheckpointHash = $checkpointHash;
        }

        $manifest = [
            'format' => 'sigilbase-evidence/1.1',
            'generated_at' => '2026-07-01T10:00:00.000000Z',
            'stream' => ['id' => $this->streamId, 'slug' => 'fixture-stream', 'name' => 'Fixture stream'],
            'range' => ['from' => 1, 'to' => $eventCount],
            'event_count' => $eventCount,
            'signing_keys' => [
                ['public_key' => $this->publicKeyHex, 'created_at' => '2026-01-01T00:00:00.000000Z', 'retired_at' => null],
            ],
        ];

        file_put_contents(
            $dir.DIRECTORY_SEPARATOR.'manifest.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR),
        );

        file_put_contents(
            $dir.DIRECTORY_SEPARATOR.'events.ndjson',
            implode("\n", array_map(canonical_encode(...), $events))."\n",
        );

        file_put_contents(
            $dir.DIRECTORY_SEPARATOR.'checkpoints.json',
            json_encode(['checkpoints' => $checkpoints], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR),
        );

        return $dir;
    }

    /**
     * Zip an extracted bundle directory (requires ext-zip; tests that need
     * this skip when it is absent).
     */
    public function zip(string $dir, string $zipPath): string
    {
        $zip = new ZipArchive;

        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new RuntimeException("could not create [{$zipPath}]");
        }

        foreach (['manifest.json', 'events.ndjson', 'checkpoints.json'] as $file) {
            $zip->addFile($dir.DIRECTORY_SEPARATOR.$file, $file);
            // A fixed entry time keeps a committed fixture byte-stable.
            $zip->setMtimeName($file, 315532800);
        }

        $zip->close();

        return $zipPath;
    }

    /**
     * Write a bundle of the events given, in order, as one stream: each
     * spec names an action, a resource and a payload, and a payload may be
     * a closure receiving the events built so far (as objects carrying
     * seq and entry_hash), which is how a receipt names the one before
     * it. The format, an optional connection.json, and a later range
     * start are options, so the collection-record rules of format 1.6 can
     * be exercised exactly, including the links a bundle that starts
     * after sequence 1 cannot show.
     *
     * @param  list<array{action: string, resource: string|null, payload: object|\Closure, actor?: string}>  $specs
     * @param  array{format?: string, connection?: array<string, mixed>|null, range_from?: int, per_checkpoint?: int}  $options
     */
    public function writeCollectionBundle(string $dir, array $specs, array $options = []): string
    {
        if (! is_dir($dir) && ! mkdir($dir, 0755, true)) {
            throw new RuntimeException("could not create [{$dir}]");
        }

        $format = $options['format'] ?? 'sigilbase-evidence/1.6';
        $rangeFrom = $options['range_from'] ?? 1;
        $perCheckpoint = $options['per_checkpoint'] ?? 2;

        $events = [];
        $prevHash = self::ZERO_HASH;

        foreach ($specs as $index => $spec) {
            $sequence = $index + 1;
            $payload = $spec['payload'] instanceof \Closure ? ($spec['payload'])($events) : $spec['payload'];
            $payloadHash = hash('sha256', canonical_encode($payload));
            $occurredAt = sprintf('2026-07-01T09:%02d:%02d.000000Z', intdiv($sequence, 60), $sequence % 60);
            $receivedAt = sprintf('2026-07-01T09:%02d:%02d.500000Z', intdiv($sequence, 60), $sequence % 60);
            $actor = $spec['actor'] ?? 'connection:fixture';

            $entryHash = hash('sha256', canonical_encode((object) [
                'v' => 1,
                'stream' => $this->streamId,
                'seq' => $sequence,
                'occurred_at' => $occurredAt,
                'received_at' => $receivedAt,
                'actor' => $actor,
                'action' => $spec['action'],
                'resource' => $spec['resource'],
                'payload_hash' => $payloadHash,
                'prev' => $prevHash,
            ]));

            $events[] = (object) [
                'v' => 1,
                'seq' => $sequence,
                'occurred_at' => $occurredAt,
                'received_at' => $receivedAt,
                'actor' => $actor,
                'action' => $spec['action'],
                'resource' => $spec['resource'],
                'payload' => $payload,
                'payload_state' => 'present',
                'payload_hash' => $payloadHash,
                'prev_hash' => $prevHash,
                'entry_hash' => $entryHash,
            ];

            $prevHash = $entryHash;
        }

        $eventCount = count($events);

        // Checkpoints over the whole history, then only those inside the
        // range are exported: a bundle that starts later carries its first
        // checkpoint's prev_checkpoint as the chain truly had it.
        $checkpoints = [];
        $prevCheckpointHash = self::ZERO_HASH;

        foreach (array_chunk($events, $perCheckpoint) as $chunk) {
            $from = $chunk[0]->seq;
            $to = $chunk[count($chunk) - 1]->seq;

            $root = bin2hex(merkle_root(array_map(
                static fn (object $event): string => (string) hex2bin($event->entry_hash),
                $chunk,
            )));

            $createdAt = sprintf('2026-07-01T10:%02d:%02d.000000Z', intdiv($to, 60), $to % 60);

            $checkpointHash = hash('sha256', canonical_encode((object) [
                'v' => 1,
                'stream' => $this->streamId,
                'from' => $from,
                'to' => $to,
                'root' => $root,
                'prev_checkpoint' => $prevCheckpointHash,
                'created_at' => $createdAt,
            ]));

            $checkpoints[] = (object) [
                'v' => 1,
                'stream' => $this->streamId,
                'from' => $from,
                'to' => $to,
                'root' => $root,
                'prev_checkpoint' => $prevCheckpointHash,
                'created_at' => $createdAt,
                'checkpoint_hash' => $checkpointHash,
                'signature' => bin2hex(sodium_crypto_sign_detached((string) hex2bin($checkpointHash), $this->secretKey)),
                'public_key' => $this->publicKeyHex,
            ];

            $prevCheckpointHash = $checkpointHash;
        }

        if ($rangeFrom > 1 && (($rangeFrom - 1) % $perCheckpoint) !== 0) {
            throw new RuntimeException('range_from must start a checkpoint');
        }

        $exportedEvents = array_values(array_filter($events, static fn (object $event): bool => $event->seq >= $rangeFrom));
        $exportedCheckpoints = array_values(array_filter($checkpoints, static fn (object $checkpoint): bool => $checkpoint->from >= $rangeFrom));

        $manifest = [
            'format' => $format,
            'generated_at' => '2026-07-01T11:00:00.000000Z',
            'stream' => ['id' => $this->streamId, 'slug' => 'sigilbase-connection-fixture', 'name' => 'Connection receipts: Fixture'],
            'range' => ['from' => $rangeFrom, 'to' => $eventCount],
            'event_count' => count($exportedEvents),
            'signing_keys' => [
                ['public_key' => $this->publicKeyHex, 'created_at' => '2026-01-01T00:00:00.000000Z', 'retired_at' => null],
            ],
        ];

        file_put_contents(
            $dir.DIRECTORY_SEPARATOR.'manifest.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR),
        );

        file_put_contents(
            $dir.DIRECTORY_SEPARATOR.'events.ndjson',
            implode("\n", array_map(canonical_encode(...), $exportedEvents))."\n",
        );

        file_put_contents(
            $dir.DIRECTORY_SEPARATOR.'checkpoints.json',
            json_encode(['checkpoints' => $exportedCheckpoints], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR),
        );

        $connectionPath = $dir.DIRECTORY_SEPARATOR.'connection.json';

        if (array_key_exists('connection', $options) && $options['connection'] !== null) {
            file_put_contents(
                $connectionPath,
                json_encode($options['connection'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR),
            );
        } elseif (is_file($connectionPath)) {
            unlink($connectionPath);
        }

        return $dir;
    }

    /**
     * Zip an extracted bundle directory with whatever bundle files it
     * holds (requires ext-zip).
     */
    public function zipAll(string $dir, string $zipPath): string
    {
        $zip = new ZipArchive;

        if ($zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE) !== true) {
            throw new RuntimeException("could not create [{$zipPath}]");
        }

        foreach (['manifest.json', 'events.ndjson', 'checkpoints.json', 'connection.json'] as $file) {
            if (! is_file($dir.DIRECTORY_SEPARATOR.$file)) {
                continue;
            }

            $zip->addFile($dir.DIRECTORY_SEPARATOR.$file, $file);
            $zip->setMtimeName($file, 315532800);
        }

        $zip->close();

        return $zipPath;
    }
}
